apiVersion: v1
kind: Service
metadata:
  name: easygen-backend-service
spec:
  type: LoadBalancer
  selector:
    app: easygen-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000